stages:
  - lint
  - dependency scan
  - build
  - staging
  - deploy

default:
  image: "node"

variables:
  COVERAGE_DIR: ./coverage
  DIST_DIR: ./build/dist/

Lint:
  stage: lint
  needs: []
  inherit:
    default: true
  script:
    - npm run lint

Dependency Scan:
  stage: dependency scan
  needs: []
  inherit:
    default: true
    variables: true
  script:
    - mkdir -p ${COVERAGE_DIR}
    - npm install
    - npm audit --json --audit-level=critical > ${COVERAGE_DIR}/audit.json
    - echo "Need to also run OWASP CLI scan"
  artifacts:
    expire_in: 1 days
    paths:
      - ${COVERAGE_DIR}

Build:
  stage: build
  needs: []
  inherit:
    default: true
  script:
    - npm install
    - npm run build
    - mkdir ./build
    - cp -r ./dist ./build/dist
  artifacts:
    expire_in: 1 days
    paths:
      - ${DIST_DIR}

Production Deploy:
  stage: deploy
  needs: [Build]
  inherit:
    default: true
    variables: true
  only:
    - main
  script:
    - npm install netlify-cli@9.16.4
    - npm run deploy -- --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod --dir ${DIST_DIR}
    - echo "netlify deployment successful"
