stages:
  - build
  - test
  - OWASP Scan

default:
  image: "node"

build dist:
  stage: build
  inherit:
    default: true
  script:
    - echo "building distributables..."
    - npm install
    - npm run build

tests:
  stage: test
  script:
    - echo "testing project....no tests available."

Security Check:
  stage: OWASP Scan
  inherit:
    default: true
  script:
    - echo "checking for security vulnerabilities.."
    - npm audit
