stages:
  - build
  - test
  - OWASP Scan
  - dockerise
  - deploy

default:
  image: "node"

variables:
  COVERAGE_DIR: ./coverage
  DIST_DIR: ./build/dist/

build dist:
  stage: build
  inherit:
    default: true
  script:
    - echo "building distributables..."
    - npm install
    - npm run build
    - mkdir ./build
    - cp -r ./dist ./build/dist
  artifacts:
    expire_in: 1 days
    paths:
      - ${DIST_DIR}

tests:
  inherit:
    default: true
  stage: test
  script:
    - npm test
    - echo "testing project....no tests available."

Security Check:
  stage: OWASP Scan
  inherit:
    default: true
    variables: true
  script:
    - mkdir -p ${COVERAGE_DIR}
    - echo "checking for security vulnerabilities.."
    - npm audit --json --audit-level=critical > ${COVERAGE_DIR}/audit.json
  artifacts:
    expire_in: 1 days
    paths:
      - ${COVERAGE_DIR}

dockerise:
  stage: dockerise
  inherit:
    default: true
    variables: true
  script:
    - echo "Docker image creation implementaiton not yet finished! Skipping this stage..."

deploy:
  stage: deploy
  inherit:
    default: true
    variables: true
  script:
    - npm install
    - npm run deploy -- --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod --dir ${DIST_DIR}
