stages:
  - lint
  - build
  - test
  - dependency scan
  - deploy

default:
  image: "node"

variables:
  COVERAGE_DIR: ./coverage
  DIST_DIR: ./build/dist/

Linting:
  stage: lint
  inherit:
    default: true
  allow_failure: true
  script:
    - npm install
    - npx browserslist@latest --update-db
    - node_modules/eslint/bin/eslint.js .

Building:
  stage: build
  inherit:
    default: true
  script:
    - echo "building distributables..."
    - npm install
    - npm run build
    - mkdir ./build
    - cp -r ./dist ./build/dist
  artifacts:
    expire_in: 1 days
    paths:
      - ${DIST_DIR}

Testing:
  inherit:
    default: true
  stage: test
  script:
    - npm test
    - echo "testing project....no tests available."

Dependency scanning:
  stage: dependency scan
  inherit:
    default: true
    variables: true
  script:
    - mkdir -p ${COVERAGE_DIR}
    - echo "checking for security vulnerabilities.."
    - npm audit --json --audit-level=critical > ${COVERAGE_DIR}/audit.json
  artifacts:
    expire_in: 1 days
    paths:
      - ${COVERAGE_DIR}

deploying:
  stage: deploy
  inherit:
    default: true
    variables: true
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
  script:
    - npm install
    - npm run deploy -- --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod --dir ${DIST_DIR}
